# Generated by Django 3.2.9 on 2022-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_rename_city_country_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale_statistics',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
